main: net.mcreator.extracore.ExtracoreprodMod
name: Extracorev2
version: 1.0.0
authors: [ExtraDev]
website: https://extradia.fr
api-version: 1.16

commands:
  extradia:
    permission: extradia.use
